all:
	g++ -std=c++11 -Wall -Wno-sign-compare -pedantic main.cpp SuffTree.cpp -o SuffTree
bench:
	g++ -std=c++11 -Wall -Wno-sign-compare -pedantic SuffTree.cpp bench.cpp -o Bench
clear:
	rm SuffTree *~
